enum ActionTypeKeys {
    // ========== Subreddit ========== //
    SUBREDDIT_REQUEST = "SUBREDDIT_REQUEST",
    SUBREDDIT_RECEIVE = "SUBREDDIT_RECEIVE",
    SUBREDDIT_INVALIDATE = "SUBREDDIT_INVALIDATE",
    
    // ========== Integration ========== //
    INTEGRATION_REQUEST = "INTEGRATION_REQUEST",
    INTEGRATION_RECEIVE = "INTEGRATION_RECEIVE",
    INTEGRATION_INVALIDATE = "INTEGRATION_INVALIDATE",
}

export default ActionTypeKeys;
